name: abnmo_test

services:
  abnmo_db:
    image: mysql:8.4
    container_name: 'mysql-test'
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - '${DB_PORT}:3306'
    volumes:
      - abnmo_mysql_test_data:/var/lib/mysql

volumes:
  abnmo_mysql_test_data:
